application:
  name: monica
  project: CHANGEME
  organization: CHANGEME
  storage:
  - name: monica-data
    type: ssd
    size: 5GB
    mount_point: /var/lib/monica/content
routers:
- name: monica-router
  routes:
  - application_name: monica
    paths:
    - "/"
